### PR TITLE
add UUID support for crystal 24 breaking changes

### PR DESCRIPTION
**Pull request by kingsleyh**
this is a fix for the SecureRandom breaking change in crystal 24 - Ive just started crystal - so the fix might be rubbish

### CODE REVIEW

**Comment by lbguilherme** [comment]
This adds UUID, which is great. But you mentioned SecureRandom, but doesn't touch it. Is it missing some commit?

**Comment by kingsleyh** [comment]
No that was everything - I’m not exactly sure why it was impacted - maybe when in crystal 23 - SecureRamdom was getting turned into a string but with UUID it doesn’t? I followed the error and fixed where it happened but I guess maybe a fix would be possible outside of RethinkDB I’m not sure

**Comment by lbguilherme** [comment]
Ok, thanks. I'll accept this and then check if anything else it needed for 0.24

**Comment by kingsleyh** [comment]
Great thanks - this is a great library - I'll try to contribute to it - I'm particularly interested in append, set_insert and joins

**Comment by lbguilherme** [comment]
Please hold on. I'm working on a substitute for this library and as soon as it is feature equivalent to this one, I'll release and replace it. I expect it in one week or two.

Actually, it might be easy to just add those here, if you will. In case you need them before that.

**Comment by lbguilherme** [comment]
@kingsleyh Take a look at https://github.com/lbguilherme/rethinkdb-lite

**Comment by kingsleyh** [comment]
wow very ambitious - looks awesome. Is the idea to start using it for the client part as a replacement for this library - and then eventually replace the server as well

**Comment by kingsleyh** [comment]
One potential issue could be the lack of windows support - I don't know if many people use rethinkdb on windows. I use OSX and Linux so personally I don't care about windows support.

**Comment by lbguilherme** [comment]
That's correct. The client is mostly easy. The server is an epic goal.

There are many things missing from Crystal right now, the most important are multi-threading and Windows support. I'm just leaving those for the future. They will be implemented much before I come close to end the server part, so I'm not really caring for now.

**Pull request merged**
